//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlDemo.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        public int SanphamID { get; set; }
        public string TenSanpham { get; set; }
    }
}
